on:
  reddit:
    url: https://reddit.com/r/FloridaMan/hot/
    config:
      format: |
        item.title = item.title
          .replace(/man|woman|person/,'hedgehog')
          .replace(/Man|Woman|Person/,'Hedgehog')
          .replace(/men|women|people/,'array of hedgehogs')
          .replace(/Men|Women|People/,'Array of Hedgehogs')
        return item;
jobs:
  twitter:
    name: post tweet
    runs-on: ubuntu-latest
    steps:
      - name: Post a tweet
        uses: ethomson/send-tweet-action@v1
        with:
          status: ${{ on.rss.outputs.title }}
          consumer-key: ${{ secrets.TWITTER_CONSUMER_KEY }}
          consumer-secret: ${{ secrets.TWITTER_CONSUMER_SECRET }}
          access-token: ${{ secrets.TWITTER_ACCESS_TOKEN }}
          access-token-secret: ${{ secrets.TWITTER_ACCESS_SECRET }}
